### PR TITLE
Allowed setting of computed attributes silently.

### PR DESCRIPTION
**Pull request by strictlyskyler**
I modified the setComputedAttributes method to allow for silent setting of said attributes – the setting of the attribute (or attributes) will need to be added to the function defined by the user instead.

I also added the sourceURL schema for Chrome Dev Tools.

### CODE REVIEW

**Comment by tommyh** [comment]
Hi,

Thank you for the contribution - a very cool way to make it more extensible.

A few thoughts:
1. What if the user doesn't want to define a custom setter function?  Can there be a sensible default defined for them?
2. The current automated tests on your pull request branch are failing.
3. Can you add tests for your new functionality?  (To make sure no one breaks it in the future)

Tom

**Comment by strictlyskyler** [comment]
Ok, I've added a default case for functions which return a value, and allowed for functions which don't.  This fixes the existing automated tests.  I've also added a new test case for each of these.

Thanks!

**Comment by strictlyskyler** [comment]
Bump.

**Comment by tommyh** [comment]
Hi,

Sorry it's taken me a while to get around to this.  Personal note: I had a child recently, so that's where most of my extra time has gone, :)

After taking a look at the pull request, I am unable to merge it in it's current form.  Here's the issue: the goal of this code is to only `set` the property on the view model if the `computed_attribute` function returns a value - which is fair enough.  But there is an unintended side-effect, what if the `computed_attribute` returns a value which is falsy (`null`, `undefined`, `false`).  This would be the base case (`computed_attribute` of falsy value), getting broken by an extra feature (silent setting).

If we take a step back, can you provide detail on why a view model having silent set's is helpful?  Is it a performance savings?  If not, and it's something totally custom, you might just want to use a custom "on change" in the view model's initialize function.  (Not sure if that's a helpful response or not, because I don't totally understand your use case).

Tom

**Comment by tommyh** [comment]
Closing this for now.  I'd be more than happy to re-open pending more information about the intended use-case and the ability for the feature to not conflict with the valid scenario of a computed attribute returning a falsy value.

**Comment by strictlyskyler** [comment]
The original reason for this was to be able to compute various values the view would render without triggering a render for each value.  Currently, each time a computed value changes, a render is triggered.  If the view does any kind of animation at all, this causes the animation to fire multiple times, repeating itself in the best case, and entering an unstable state in the worst case.

Ultimately, the need is to have the ability to compute data for a view to render without strictly tying each computed value with a render – the render needs to happen only once, when all of the various values are finished computing.

**Pull request closed without merging**
